server:
  port: 8091
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/wrm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: root